package cosac;

public enum SceneType {
    ADMIN_VIEW,
    ADMIN_ORDER_VIEW,
    ADMIN_USER_VIEW,
    ADMIN_RESTRICTION_VIEW,
    ADMIN_MENU_VIEW,
    ADMIN_ADD_USER_VIEW,
    ADMIN_LOCK_USER_VIEW,
    ADMIN_ADD_RESTRICTION_VIEW,
    LOGIN,
}
