package cosac.rmi;

public enum Post {

    INSERT_USER_DATA_SET,
    INSERT_RESTRICTION_DATA_SET,
    INSERT_FOOD_DATA_SET,
    INSERT_SECTION_DATA_SET,

    UPDATE_USER_DATA_SET,
    UPDATE_RESTRICTION_DATA_SET

}
