package cosac.rmi;

public enum Protocol {

    GET_USER_DATA_SETS,
    GET_FOOD_DATA_SETS,
    GET_RESTRICTION_DATA_SETS,
    GET_SECTION_DATA_SETS,
    GET_ORDER_DATA_SETS,

    SET_USER_DATA_SETS,
    SET_FOOD_DATA_SETS,
    SET_RESTRICTION_DATA_SETS,
    SET_SECTION_DATA_SETS,
    SET_ORDER_DATA_SETS

}
